<?php
define( 'TZS_RECORDS_PER_PAGE', 20 );
define( 'TZS_RECORDS_PER_PAGE_ARRAY', '10,20,30,40,50' );
define( 'TZS_FEEDBACKS_PER_PAGE', 25 );
define( 'TZS_FEEDBACK_MIN_LEN', 5 );
define( 'TZS_MAX_PAGES', 10 );
define( 'TZS_MAX_PAGES_2', TZS_MAX_PAGES/2 );
define( 'TZS_PR_PUBLICATION_MIN_DAYS', 7 );
define( 'TZS_AU_EXPIRATION_MIN_DAYS', 7 );
define( 'TZS_PR_MAX_IMAGES', 7 );
define( 'TZS_PR_ROOT_CATEGORY_PAGE_ID', 164 );
define( 'TZS_AU_ROOT_CATEGORY_PAGE_ID', 166 );
?>